name: Security Scan Gate

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-gate:
    name: Enforced Security Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec (hard fail)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false

      - name: Run Checkov (hard fail)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: false
